In [1]:
import pandas as pd
df=pd.read_csv("customer_shopping_behavior.csv")
print(df.head())

   Customer ID  Age Gender Item Purchased  Category  Purchase Amount (USD)  \
0            1   55   Male         Blouse  Clothing                     53
1            2   19   Male        Sweater  Clothing                     64
2            3   50   Male          Jeans  Clothing                     73
3            4   21   Male        Sandals  Footwear                     90
4            5   45   Male         Blouse  Clothing                     49

        Location Size      Color  Season  Review Rating Subscription Status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   Shipping Type Discount Applied Promo Code Used  Previous Purchases  \
0        Express              Yes             Yes                  14
1        Express              Yes             Yes                   2
2  Free Shipping              Yes             Yes                  23
3   Next Day Air              Yes             Yes                  49
4  Free Shipping              Yes             Yes                  31

  Payment Method Frequency of Purchases
0          Venmo            Fortnightly
1           Cash            Fortnightly
2    Credit Card                 Weekly
3         PayPal                 Weekly
4         PayPal               Annually

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
import numpy as np

df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [17]:
df["Review Rating"]=df.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.median()))

In [9]:
df.columns = df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [13]:
# create a column
labels = ['Young_adult','adult','Middle_aged','senior']
df['age_group']=pd.qcut(df['age'],q = 4,labels = labels)

In [15]:
df[['age','age_group']].head(6)

   age    age_group
0   55  Middle_aged
1   19  Young_adult
2   50  Middle_aged
3   21  Young_adult
4   45  Middle_aged
5   46  Middle_aged

In [17]:
frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [19]:
df[['purchase_frequency_days','frequency_of_purchases']].head()

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually

In [21]:
(df['discount_applied']==df['promo_code_used']).all()

True

In [23]:
df=df.drop('promo_code_used',axis=1)

In [25]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [60]:
!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.6.0-cp312-cp312-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
    --------------------------------------- 0.3/16.5 MB ? eta -:--:--
    --------------------------------------- 0.3/16.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/16.5 MB 929.6 kB/s eta 0:00:18
   - -------------------------------------- 0.8/16.5 MB 905.5 kB/s eta 0:00:18
   -- ------------------------------------- 1.0/16.5 MB 986.7 kB/s eta 0:00:16
   --- ------------------------------------ 1.3/16.5 MB 1.0 MB/s eta 0:00:15
   --- ------------------------------------ 1.6/16.5 MB 1.1 MB/s eta 0:00:14
   ---- ----------------------------------- 1.8/16.5 MB 1.2 MB/s eta 0:00:13
   ----- ---------------------------------- 2.4/16.5 MB 1.2 MB/s eta 0:00:12
   ------ --------------------------------- 2.9/16.5 MB 1.3 MB/s eta 0:00:11
   ------- -------------------------------- 3.1/16.5 MB 1.4 MB/s eta 0:00:10
   -------- ------------------------------- 3.7/16.5 MB 1.5 MB/s eta 0:00:09
   ---------- ----------------------------- 4.2/16.5 MB 1.5 MB/s eta 0:00:09
   ---------- ----------------------------- 4.5/16.5 MB 1.5 MB/s eta 0:00:08
   ------------ --------------------------- 5.0/16.5 MB 1.6 MB/s eta 0:00:08
   ------------- -------------------------- 5.5/16.5 MB 1.6 MB/s eta 0:00:07
   --------------- ------------------------ 6.3/16.5 MB 1.7 MB/s eta 0:00:06
   --------------- ------------------------ 6.6/16.5 MB 1.8 MB/s eta 0:00:06
   --------------- ------------------------ 6.6/16.5 MB 1.8 MB/s eta 0:00:06
   --------------- ------------------------ 6.6/16.5 MB 1.8 MB/s eta 0:00:06
   ---------------- ----------------------- 6.8/16.5 MB 1.6 MB/s eta 0:00:07
   ----------------- ---------------------- 7.1/16.5 MB 1.5 MB/s eta 0:00:07
   ----------------- ---------------------- 7.3/16.5 MB 1.5 MB/s eta 0:00:07
   ------------------ --------------------- 7.6/16.5 MB 1.5 MB/s eta 0:00:06
   ------------------- -------------------- 8.1/16.5 MB 1.5 MB/s eta 0:00:06
   -------------------- ------------------- 8.7/16.5 MB 1.6 MB/s eta 0:00:05
   ---------------------- ----------------- 9.4/16.5 MB 1.6 MB/s eta 0:00:05
   ------------------------ --------------- 10.0/16.5 MB 1.7 MB/s eta 0:00:04
   ------------------------- -------------- 10.5/16.5 MB 1.7 MB/s eta 0:00:04
   -------------------------- ------------- 11.0/16.5 MB 1.7 MB/s eta 0:00:04
   --------------------------- ------------ 11.5/16.5 MB 1.8 MB/s eta 0:00:03
   ----------------------------- ---------- 12.3/16.5 MB 1.8 MB/s eta 0:00:03
   ------------------------------- -------- 12.8/16.5 MB 1.8 MB/s eta 0:00:02
   -------------------------------- ------- 13.4/16.5 MB 1.8 MB/s eta 0:00:02
   --------------------------------- ------ 13.9/16.5 MB 1.9 MB/s eta 0:00:02
   ---------------------------------- ----- 14.4/16.5 MB 1.9 MB/s eta 0:00:02
   ------------------------------------ --- 14.9/16.5 MB 1.9 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.5 MB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.5 MB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 16.0/16.5 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 1.9 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0

In [62]:
!pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.34)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [27]:
#connect to the mysql
host="localhost"       
user="root" 
password=""
port="3306"
database="customer_behavior" 

from sqlalchemy import create_engine

engine=create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")

In [29]:
# load dataframe to mysql
table_name="customer"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print(f"Data Successfully loaded into table '{table_name}'in database '{database}'.")

Data Successfully loaded into table 'customer'in database 'customer_behavior'.